# Generated by Django 2.2.5 on 2020-12-25 12:52

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='dadfdf.jpeg', upload_to=''),
            preserve_default=False,
        ),
    ]
